export const categoryByUrlConstants = {
    CATEGORY_BY_URL_GET: 'CATEGORY_BY_URL_GET',
    CATEGORY_BY_URL_SUCCESS: 'CATEGORY_BY_URL_SUCCESS',
    CATEGORY_BY_URL_FAILURE: 'CATEGORY_BY_URL_FAILURE',
};